# Generated by Django 4.1.6 on 2023-02-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0003_alter_catagory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
