# Generated by Django 4.1.6 on 2023-03-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0006_alter_product_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='Catagory_type',
            field=models.CharField(default='pesticides', max_length=40),
        ),
    ]
