# Generated by Django 4.1.6 on 2023-03-03 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0007_catagory_catagory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='Catagory_type',
        ),
        migrations.AddField(
            model_name='catagory',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopp_app.catagory_type'),
        ),
    ]
