# Generated by Django 4.1.6 on 2023-03-07 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0014_catagory_type2_product_type1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Type1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopp_app.catagory_type2'),
        ),
    ]
