# Generated by Django 4.1.6 on 2023-03-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopp_app', '0016_catagory_type2_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory_type2',
            name='category',
        ),
    ]
