# Generated by Django 4.1.6 on 2023-02-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
