# Generated by Django 4.1.6 on 2023-02-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_account_is_active_alter_user_address_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
